### ISSUE TITLE
Banner değişiklikleri

### ISSUE THREAD

**Issue by EnesFly** [EnesFly/match-medic#45]
DoD:

- github ana sayfasındaki mockup'a güre güncellenecektir.
- slogan componenti eklenecektir
- fonksiyon ve görsel tasarım kapsam dışıdır.
- Footer'daki "FAQ"  ve "Terms and Conditions" linklenebilir olacaktır

**Comment by aefeakn** [comment]
preRequisite => Routing?? Linklenebilir derken <a/> gibi sayfada bir yere atması gibi mi yoksa ayrı sayfalara gibi mi?

**Comment by aefeakn** [comment]
-SVG is sent in grey color from firebase we ll check that
