### ISSUE TITLE
Mesaj formunun güncellenmesi

### ISSUE THREAD

**Issue by EnesFly** [EnesFly/match-medic#84]
DoD:

- son mockup'a göre güncellencektir
- - Drag and Drop bölgesi ve uploaded files bölgesi eklenecektir.

**Comment by aefeakn** [comment]
![WhatsApp Image 2024-03-18 at 17 04 26](https://github.com/EnesFly/match-medic/assets/60469773/62819acf-aca6-4169-8363-b3c9540e010b)
